### ISSUE TITLE
Consider name change

### ISSUE THREAD

**Issue by zautumnz** [zacanger/alert-node#5]
The `alert` package is owned by @iclanzan. I tweeted them to see if they would hand that over, since there's no code there. If not, switching to `isomorphic-alert` or similar might be nice.

**Comment by iclanzan** [comment]
I haven't seen the tweet, but I can look into this next week.

**Comment by zautumnz** [comment]
Thank you, I appreciate it!

**Comment by iclanzan** [comment]
Shoot, forgot about this. Would the `alert` name still interest you? If so, what is your NPM username?

**Comment by zautumnz** [comment]
Oh, no worries, I was just clearing out issues! Yeah I would definitely still be interested in that! My username on npm is `zacanger`

**Comment by iclanzan** [comment]
I have added you as a maintainer, feel free to remove me.

**Comment by zautumnz** [comment]
Thanks so much!
